### ISSUE TITLE
deadpos v2.1 Issue with PDB 11

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#12]
// 11 - P1112386 Mrs. W. J. Baird (2) British Chess Magazine, p. 136, 03/1903
>>> 6k1/8/6K1/8/8/8/8/8 b >>= r >>= flip >>= m >>= m >>= flip >>= r >>= flip >>= #1 (p)  
h5xRg6 g8h7 h5h4 h6xPh7 then h7h8q#                                             
f5xRg6 g8h7 f5f4 h6xPh7 then h7h8q#                                             
g5xPg6 g8h7 g5f6 h6xPh7 then h7h8q#                                             
g5xPg6 g8h7 g5f6 h6xPh7 then h7h8r#                                             
g5xPg6 g8h7 g5h4 h6xPh7 then h7h8q#                                             
g5xPg6 g8h7 g5g4 h6xPh7 then h7h8q#                                             
g5xPg6 g8h7 g5f4 h6xPh7 then h7h8q#                                             
nsols 7

This is now missing the actual solution. Should be:
[...]
f6xPg6 flip then g8h8 f6f7 flip h7xPg6 flip then g6g7#
nsols 8

**Comment by miguel-ambrona** [comment]
This is because the position after the last flip is illegal. With the new convention of excluding illegal positions, it was filtered out.

I'll modify `flip` so that the position after a flip becomes the "game array" thus it is legal by default.
