### ISSUE TITLE
Interesting discovery with PDB P0005387

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#15]
// 3 - P0005387 Nikita M. Plaksin 6557 feenschach 109 11/1993
>>> 8/8/8/8/K7/8/b7/kB6 b >>= r >>= h=1
e4xQb1 then a4a3 b1e4 stalemate                                                 
a3xPa4 then b1a2 stalemate cook?                                                
nsols 2 

Actually what I supplied was:
b ? ? >>= r1 >>= =1

So the unique solution would be:
a3xPa4 then b1a2 stalemate

Other points:
(1) A h#3 is *not* regarded as having a cooked/short solution if Black can mate White after bwbwb. Similarly for stalemates and for dead position. *White* will play the final move in the stipulated directplay or helpplay; *Black* in selfplay. Only if there is a solution which is short by n.0 moves does it count as cooked/short.
(2) On the other hand, when we compute whether a position is living/dead, we are looking for mates from either side.
(3) Nevertheless, you've made an interesting discovery! Not sure how to adjust the stipulation elegantly to incorporate this duplex play

**Comment by miguel-ambrona** [comment]
You are right, the syntax `=1` is not supported, so I wrote `h=1` instead (thinking that if it is just one move, it does not matter if it is cooperative or competitive). It should be `h=0.5` instead.

I will also exclude shorter solutions unless they have the same parity as the expected solution.

This issue will be resolved automatically. I guess you'll remember your discovery!
