### ISSUE TITLE
challenge with PDB 25 castling

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#17]
There are 3 queries posed for this position.
castling? This should definitely be K only
r? This is all correct!
#2? We discussed this yesterday, and I think it's not implemented yet, but I want to record the requirement here. DP is used instead of castling convention. So if the solution requires castling, then it would check "castling?" Ultimately, if those fail, it will be interesting to engage with conventions but they are a lot harder, particularly when they come in multiples (PRA, RS, AP, SPRA etc...).

```
// 25 - P1244258 Andrew Buchanan Retros mailing list 01/2001
>>> 8/8/2Q1N3/3B4/2PP4/3Nk2P/2P5/B2RK2R w >>= castling
K
-
nsols 2                                                                        

>>> 8/8/2Q1N3/3B4/2PP4/3Nk2P/2P5/B2RK2R w >>= #2
e1g1 ... #                                                                      
nsols 1
```

**Comment by miguel-ambrona** [comment]
> castling? This should definitely be K only

You can get this result with the (non-documented) `legal` command:
`8/8/2Q1N3/3B4/2PP4/3Nk2P/2P5/B2RK2R w >>= legal >>= castling`.

It is slightly more powerful that the default legality check (it looks with depth = 2).
When the default legality checks become more powerful, this will be solved correctly.

**Comment by miguel-ambrona** [comment]
I prefer not to complicate things with a hard-coded convention logic.

What you request can now be performed semi-automatically as:
```
>>> 8/8/2Q1N3/3B4/2PP4/3Nk2P/2P5/B2RK2R w >>= legal >>= castling
K
nsols 1                                                                        

>>> 8/8/2Q1N3/3B4/2PP4/3Nk2P/2P5/B2RK2R w K >>= #2
e1g1 ... #                                                                      
nsols 1
```

That is, I first figure out that `K` is the only valid castling right and then plug it in the second query.

**Comment by andrew-buchanan** [comment]
Yes I think that works very well. I think the use of legal in this way is good.
