### ISSUE TITLE
PDB 22 Baird problem repaired!

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#18]
Nit: we should have marked PDB 22 as cooked, but much more interestingly there is a better fix than what was discussed in PDB!

It's sound and has a unit less than the cooked version. 296/297 solutions have a queen. I will post in PDB.

Deadpos Analyzer version 2.1
//22 - P1185584 Mrs. W. J. Baird La Strategie (no queens!) cooked
//version AB&MA
8/8/4N1p1/1P1k4/8/2K5/8/8 b >>= r >>= r >>= h#1
>>> 8/8/4N1p1/1P1k4/8/2K5/8/8 b >>= r >>= r >>= h#1
c5xRe6 h7xRg6 then e6d6 g6g5#
nsols 297

**Comment by andrew-buchanan** [comment]
Have posted our repair as https://pdb.dieschwalbe.de/P1414378.
Our first collaborative composition!

**Comment by miguel-ambrona** [comment]
Nice!
The credit should be yours, I only wrote the software :D

I'll replace PDB 22 with this.

I'll let you close this issue.
