### ISSUE TITLE
PDB 36 P1338362 would like more info

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#20]
This is a good example of a problem where "terse" output is insufficient.

Deadpos reports:
e4f3ep then b2b1r c2b1 stalemate   
nsols 1

which is correct as far as it goes, but here is the level of the manual solution:

R: 1. exf3ep, dann 1. b1=T Kxb1=
with living alternative:
R: 1. exf3ep, dann 1. b1=T f5 2. Tb2,Tc1#
Tries:
R: 1. exf3ep, dann 1. b1=D,L+? dead because Kxb1= forced
R: 1. exf3ep, dann 1. b1=S? dead because alternative f5 2. Sc3= is still a pat

All of these lines must have been found at some point, but they are simply not being reported. Grep & excel are powerful: we can handle more output.

**Comment by miguel-ambrona** [comment]
I believe this is now supported by v2.3.

**Comment by andrew-buchanan** [comment]
Great stuff!
