### ISSUE TITLE
Can't run 48-51 in PDB2-HDP.txt

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#26]
I have run PDB2-HDP.txt, generating PDB2-HDP.out. The first 47 are all sound with no issues, and I have marked them in PDB as C+ Deadpos 2.2. The length is up to 2.5. 

However PDB2 48 hung the two times I tried to run it. Its length is 3.0. I think it's just some kind of resourcing issue in ubuntu. No reason to believe there is any more serious issue.

If you have a chance to run these please on your superior hardware I would be very grateful. They are only 3.0 & 3.5 in length.

//48 - P1411201 Andrew Buchanan Joachim Hambros
1q1n4/P1P2P2/8/2k1K3/8/8/1p3p1p/2R1N1B1 b >>= hdp3.0
//49 - P1411202 Siegfried Hornecker Andrew Buchanan
4k1K1/3rPNP1/4nP2/8/8/8/5p2/8 b >>= hdp3.0
//50 - P1411203 Andrew Buchanan Per Olin
2n2N2/1P1P1P2/2k4K/8/8/8/2p5/8 w >>= hdp3.5
//51 - P1411204 James Malcom Siegfried Hornecker
4k3/P2b4/3P4/6PK/8/8/2p5/8 w >>= hdp3.5

I think they were all validated by a much earlier version of deadpos, but might as well get them running against v2.2

**Comment by miguel-ambrona** [comment]
Note that the file you are referring to is not currently part of this repository.

Nevertheless, I executed those with v2.3. Here are the results:

```
// P48
>>> 1q1n4/P1P2P2/8/2k1K3/8/8/1p3p1p/2R1N1B1 b >>= hdp3.0
b2c1b a7b8b h2g1b c7d8b f2e1b f7f8b DP (insufficient material) 1B1B1B2/8/8/2k1K3/8/8/8/2b1b1b1 b - - 0 4
nsols 1

// P49
>>> 4k1K1/3rPNP1/4nP2/8/8/8/5p2/8 b >>= hdp3.0 >>= legal
f2f1q g8h7 f1f6 g7g8b e6f8 e7f8q DP (e8f8=) 4kQB1/3r1N1K/5q2/8/8/8/8/8 b - - 0 4
nsols 1

// P50
>>> 2n2N2/1P1P1P2/2k4K/8/8/8/2p5/8 w >>= hdp3.5
d7c8n c2c1r f8d7 c6d7 f7f8b c1c8 b7c8q DP (d7c8 insufficient material)  2Q2B2/3k4/7K/8/8/8/8/8 b - - 0 4      
nsols 1

// P51
>>> 4k3/P2b4/3P4/6PK/8/8/2p5/8 w >>= hdp3.5 >>= legal
h5g6 c2c1q a7a8q c1c8 a8h1 c8c3 h1h8 DP (c3h8=) 4k2Q/3b4/3P2K1/6P1/8/2q5/8/8 b - - 4 4  
nsols 1
```

**Comment by miguel-ambrona** [comment]
We can borrow test vectors from PDB, but I don't think updating PDB in an automated way should be a goal here.
