### ISSUE TITLE
Support half-duplex

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#29]
At some future point it would be good to have half-duplex implemented as a qualifier for solving. This means that the player who achieves the aim (mater, stalemater, "deader") is Black instead of White. (except selfplay White instead of Black). Not urgent.

**Comment by andrew-buchanan** [comment]
But really not needed for now. Just put it as aide-memoire.

**Comment by andrew-buchanan** [comment]
Actually, on examination, there are a lot of Baird problems which use half-duplex

**Comment by miguel-ambrona** [comment]
Hi Andrew, this is already supported.
