### ISSUE TITLE
New (WIP) version 2.3 of deadpos crashed

### ISSUE THREAD

**Issue by andrew-buchanan** [miguel-ambrona/deadpos#34]
Deadpos Analyzer version 2.3
K7/3P4/8/3kP3/8/8/8/8 w >>= r >>= h=1
>>> K7/3P4/8/3kP3/8/8/8/8 w >>= r >>= h=1
Traceback (most recent call last):       | 19.73% [00:00:00 / 00:00:00]
  File "/home/dawson/deadpos/src/deadpos.py", line 408, in <module>
    main()
  File "/home/dawson/deadpos/src/deadpos.py", line 400, in main
    positions, n = process_cmd(positions, cmd)
  File "/home/dawson/deadpos/src/deadpos.py", line 366, in process_cmd
    return solve(cmd, positions)
  File "/home/dawson/deadpos/src/deadpos.py", line 244, in solve
    (solutions, n) = solver_call(cmd, pos, progress_bar)
  File "/home/dawson/deadpos/src/deadpos.py", line 198, in solver_call
    history = history[:-1] + ["(" + explain_alive(b.fen()) + ")"] + history[-1:]
  File "/home/dawson/deadpos/src/solver.py", line 190, in explain_alive
    if not mate_with_white or len(mate_with_white) > len(mate_with_black):
TypeError: object of type 'NoneType' has no len()

This is P1004393 according to PDB has 2 solutions:
1) R: 1. Ke6xDd5, dann 1. Ke7 d8=T=
1) R: 1. Kc5xTd5, dann 1. Kc6 d8=D=

**Comment by andrew-buchanan** [comment]
Also this crashes in the same way
//18 - P0005560 Bruno Stubenrauch Erich Bartel Hans Gruber
8/8/8/8/3N4/3k4/1P6/1K1B4 w >>= r >>= h=1
8/8/8/8/3P4/3k4/1P6/1K1B4 w >>= r >>= h=1

**Comment by miguel-ambrona** [comment]
Thanks for the feedback!

It's pretty clear from the error how I messed up yesterday.

**Comment by miguel-ambrona** [comment]
This is fixed now.

Those two problems now give this output:

```
>>> K7/3P4/8/3kP3/8/8/8/8 w >>= r >>= h=1 >>= legal
↶e6xQd5 e6e7 d7d8r (living alternative e5e6 e7f8 e6e7 f8e7 d7d8q#) stalemate K7/3Pk3/8/3QP3/8/8/8/8 w - - 1 2
↶d6xQd5 illegal d6e7 d7d8r (living alternative e5e6 e7f8 e6e7 f8e7 d7d8q#) stalemate K7/3Pk3/8/3QP3/8/8/8/8 w - - 1 2
↶d6xRd5 illegal d6c6 d7d8q (living alternative e5e6 c6c7 e6e7 c7b6 d7d8q b6c6 e7e8q#) stalemate K7/3P4/2k5/3RP3/8/8/8/8 w - - 1 2
↶c5xRd5 c5c6 d7d8q (living alternative e5e6 c6c7 e6e7 c7b6 d7d8q b6c6 e7e8q#) stalemate K7/3P4/2k5/3RP3/8/8/8/8 w - - 1 2
nsols 2
```

```
>>> 8/8/8/8/3N4/3k4/1P6/1K1B4 w >>= r >>= h=1 >>= legal
↶e2xBd3 illegal e2d1 d4f3 (living alternative b2b3 d1d2 b3b4 d2e3 b4b5 e3d4 b5b6 d4c3 b6b7 c3d4 b7b8q d4c3 b1a2 c3d4 d3b1 d4d5 b1c2 d5c6 b8h2 c6b7 c2b1 b7a8 a2a3 a8b7 a3a4 b7c6 a4a5 c6d7 a5a6 d7c6 a6a5 c6b7 h2d2 b7a8 a5a6 a8b8 d2d8#) stalemate 8/8/8/8/3N4/3B4/1P6/1K1k4 w - - 0 2
↶d2xBd3 d2d1 d4f3 (living alternative b2b3 d1d2 b3b4 d2e3 b4b5 e3d4 b5b6 d4c3 b6b7 c3d4 b7b8q d4c3 b1a2 c3d4 d3b1 d4d5 b1c2 d5c6 b8h2 c6b7 c2b1 b7a8 a2a3 a8b7 a3a4 b7c6 a4a5 c6d7 a5a6 d7c6 a6a5 c6b7 h2d2 b7a8 a5a6 a8b8 d2d8#) stalemate 8/8/8/8/3N4/3B4/1P6/1K1k4 w - - 0 2
nsols 1

>>> 8/8/8/8/3P4/3k4/1P6/1K1B4 w >>= r >>= h=1 >>= legal
↶c4xQd3 c4b4 d3a6 (living alternative b2b3 b4a5 b3b4 a5b6 b4b5 b6b7 d4d5 b7a8 b5b6 a8b8 d5d6 b8c8 b6b7 c8b7 d6d7 b7b8 d7d8q b8a7 b1a2 a7b7 a2a3 b7a7 a3a4 a7b7 a4a5 b7a7 d3a6#) stalemate 8/8/8/8/1k1P4/3Q4/1P6/1K1B4 w - - 1 2
↶c3xQd3 illegal c3b4 d3a6 (living alternative b2b3 b4a5 b3b4 a5b6 b4b5 b6b7 d4d5 b7a8 b5b6 a8b8 d5d6 b8c8 b6b7 c8b7 d6d7 b7b8 d7d8q b8a7 b1a2 a7b7 a2a3 b7a7 a3a4 a7b7 a4a5 b7a7 d3a6#) stalemate 8/8/8/8/1k1P4/3Q4/1P6/1K1B4 w - - 1 2
nsols 1
```
